/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface nicslulibConstants {
  public final static int NICSLU_GENERAL_FAIL = nicslulibJNI.NICSLU_GENERAL_FAIL_get();
  public final static int NICSLU_ARGUMENT_ERROR = nicslulibJNI.NICSLU_ARGUMENT_ERROR_get();
  public final static int NICSLU_MEMORY_OVERFLOW = nicslulibJNI.NICSLU_MEMORY_OVERFLOW_get();
  public final static int NICSLU_FILE_CANNOT_OPEN = nicslulibJNI.NICSLU_FILE_CANNOT_OPEN_get();
  public final static int NICSLU_MATRIX_STRUCTURAL_SINGULAR = nicslulibJNI.NICSLU_MATRIX_STRUCTURAL_SINGULAR_get();
  public final static int NICSLU_MATRIX_NUMERIC_SINGULAR = nicslulibJNI.NICSLU_MATRIX_NUMERIC_SINGULAR_get();
  public final static int NICSLU_MATRIX_INVALID = nicslulibJNI.NICSLU_MATRIX_INVALID_get();
  public final static int NICSLU_MATRIX_ENTRY_DUPLICATED = nicslulibJNI.NICSLU_MATRIX_ENTRY_DUPLICATED_get();
  public final static int NICSLU_THREADS_NOT_INITIALIZED = nicslulibJNI.NICSLU_THREADS_NOT_INITIALIZED_get();
  public final static int NICSLU_MATRIX_NOT_INITIALIZED = nicslulibJNI.NICSLU_MATRIX_NOT_INITIALIZED_get();
  public final static int NICSLU_SCHEDULER_NOT_INITIALIZED = nicslulibJNI.NICSLU_SCHEDULER_NOT_INITIALIZED_get();
  public final static int NICSLU_SINGLE_THREAD = nicslulibJNI.NICSLU_SINGLE_THREAD_get();
  public final static int NICSLU_THREADS_INIT_FAIL = nicslulibJNI.NICSLU_THREADS_INIT_FAIL_get();
  public final static int NICSLU_MATRIX_NOT_ANALYZED = nicslulibJNI.NICSLU_MATRIX_NOT_ANALYZED_get();
  public final static int NICSLU_MATRIX_NOT_FACTORIZED = nicslulibJNI.NICSLU_MATRIX_NOT_FACTORIZED_get();
  public final static int NICSLU_NUMERIC_OVERFLOW = nicslulibJNI.NICSLU_NUMERIC_OVERFLOW_get();
  public final static int NICSLU_USE_SEQUENTIAL_FACTORIZATION = nicslulibJNI.NICSLU_USE_SEQUENTIAL_FACTORIZATION_get();
  public final static int NICSLU_BIND_THREADS_FAIL = nicslulibJNI.NICSLU_BIND_THREADS_FAIL_get();
}
