/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "nicslu.h"
#include "nicslu_util.h"


typedef uint__t uintArray;

SWIGINTERN uintArray *new_uintArray(int nelements){
  return (uint__t *) calloc(nelements,sizeof(uint__t));
}
SWIGINTERN void delete_uintArray(uintArray *self){
  free(self);
}
SWIGINTERN uint__t uintArray_getitem(uintArray *self,int index){
  return self[index];
}
SWIGINTERN void uintArray_setitem(uintArray *self,int index,uint__t value){
  self[index] = value;
}
SWIGINTERN uint__t *uintArray_cast(uintArray *self){
  return self;
}
SWIGINTERN uintArray *uintArray_frompointer(uint__t *t){
  return (uintArray *) t;
}

typedef real__t doubleArray;

SWIGINTERN doubleArray *new_doubleArray(int nelements){
  return (real__t *) calloc(nelements,sizeof(real__t));
}
SWIGINTERN void delete_doubleArray(doubleArray *self){
  free(self);
}
SWIGINTERN real__t doubleArray_getitem(doubleArray *self,int index){
  return self[index];
}
SWIGINTERN void doubleArray_setitem(doubleArray *self,int index,real__t value){
  self[index] = value;
}
SWIGINTERN real__t *doubleArray_cast(doubleArray *self){
  return self;
}
SWIGINTERN doubleArray *doubleArray_frompointer(real__t *t){
  return (doubleArray *) t;
}

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_nicsluJNI_new_1uintArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  uintArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (uintArray *)new_uintArray(arg1);
  *(uintArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_delete_1uintArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  uintArray *arg1 = (uintArray *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uintArray **)&jarg1; 
  delete_uintArray(arg1);
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_uintArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  uintArray *arg1 = (uintArray *) 0 ;
  int arg2 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(uintArray **)&jarg1; 
  arg2 = (int)jarg2; 
  result = uintArray_getitem(arg1,arg2);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_uintArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3) {
  uintArray *arg1 = (uintArray *) 0 ;
  int arg2 ;
  uint__t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(uintArray **)&jarg1; 
  arg2 = (int)jarg2; 
  {
    arg3 = (uint__t)jarg3;
  }
  uintArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_uintArray_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  uintArray *arg1 = (uintArray *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(uintArray **)&jarg1; 
  result = (uint__t *)uintArray_cast(arg1);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_uintArray_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  uint__t *arg1 = (uint__t *) 0 ;
  uintArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(uint__t **)&jarg1; 
  result = (uintArray *)uintArray_frompointer(arg1);
  *(uintArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_new_1doubleArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  doubleArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (doubleArray *)new_doubleArray(arg1);
  *(doubleArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_delete_1doubleArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(doubleArray **)&jarg1; 
  delete_doubleArray(arg1);
}


SWIGEXPORT jdouble JNICALL Java_nicsluJNI_doubleArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jdouble jresult = 0 ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  real__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  arg2 = (int)jarg2; 
  result = doubleArray_getitem(arg1,arg2);
  {
    jresult = (jdouble)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_doubleArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jdouble jarg3) {
  doubleArray *arg1 = (doubleArray *) 0 ;
  int arg2 ;
  real__t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  arg2 = (int)jarg2; 
  {
    arg3 = (real__t)jarg3;
  }
  doubleArray_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_doubleArray_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  doubleArray *arg1 = (doubleArray *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(doubleArray **)&jarg1; 
  result = (real__t *)doubleArray_cast(arg1);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_doubleArray_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  real__t *arg1 = (real__t *) 0 ;
  doubleArray *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(real__t **)&jarg1; 
  result = (doubleArray *)doubleArray_frompointer(arg1);
  *(doubleArray **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1GENERAL_1FAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-1));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1ARGUMENT_1ERROR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-2));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MEMORY_1OVERFLOW_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-3));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1FILE_1CANNOT_1OPEN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-4));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1STRUCTURAL_1SINGULAR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-5));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1NUMERIC_1SINGULAR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-6));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1INVALID_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-7));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1ENTRY_1DUPLICATED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-8));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1THREADS_1NOT_1INITIALIZED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-9));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1NOT_1INITIALIZED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-10));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1SCHEDULER_1NOT_1INITIALIZED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-11));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1SINGLE_1THREAD_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-12));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1THREADS_1INIT_1FAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-13));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1NOT_1ANALYZED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-14));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1MATRIX_1NOT_1FACTORIZED_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-15));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1NUMERIC_1OVERFLOW_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((-16));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1USE_1SEQUENTIAL_1FACTORIZATION_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((+1));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NICSLU_1BIND_1THREADS_1FAIL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)((+2));
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1flag_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  bool__t *arg2 = (bool__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(bool__t **)&jarg2; 
  if (arg1) (arg1)->flag = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1flag_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  bool__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (bool__t *) ((arg1)->flag);
  *(bool__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1stat_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->stat = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1stat_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->stat);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1cfgi_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->cfgi = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1cfgi_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->cfgi);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1cfgf_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->cfgf = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1cfgf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->cfgf);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1n_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->n = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1n_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->n);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1nnz_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->nnz = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1nnz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->nnz);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1ax_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->ax = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1ax_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->ax);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1ai_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->ai = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1ai_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->ai);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1ap_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->ap = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1ap_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->ap);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1rhs_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->rhs = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1rhs_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->rhs);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1row_1perm_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->row_perm = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1row_1perm_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->row_perm);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1row_1perm_1inv_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->row_perm_inv = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1row_1perm_1inv_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->row_perm_inv);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1col_1perm_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->col_perm = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1col_1perm_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->col_perm);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1col_1perm_1inv_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->col_perm_inv = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1col_1perm_1inv_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->col_perm_inv);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1col_1scale_1perm_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->col_scale_perm = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1col_1scale_1perm_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->col_scale_perm);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1row_1scale_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->row_scale = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1row_1scale_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->row_scale);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1cscale_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->cscale = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1cscale_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->cscale);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1pivot_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  int__t *arg2 = (int__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(int__t **)&jarg2; 
  if (arg1) (arg1)->pivot = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1pivot_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  int__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (int__t *) ((arg1)->pivot);
  *(int__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1pivot_1inv_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  int__t *arg2 = (int__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(int__t **)&jarg2; 
  if (arg1) (arg1)->pivot_inv = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1pivot_1inv_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  int__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (int__t *) ((arg1)->pivot_inv);
  *(int__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1lu_1nnz_1est_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->lu_nnz_est = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1lu_1nnz_1est_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->lu_nnz_est);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1lu_1nnz_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->lu_nnz = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1lu_1nnz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->lu_nnz);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1l_1nnz_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->l_nnz = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1l_1nnz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->l_nnz);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1u_1nnz_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = (size_t)jarg2; 
  if (arg1) (arg1)->u_nnz = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1u_1nnz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->u_nnz);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1ldiag_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  if (arg1) (arg1)->ldiag = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1ldiag_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  real__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (real__t *) ((arg1)->ldiag);
  *(real__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1lu_1array_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->lu_array = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1lu_1array_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void *) ((arg1)->lu_array);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1up_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(size_t **)&jarg2; 
  if (arg1) (arg1)->up = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1up_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (size_t *) ((arg1)->up);
  *(size_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1llen_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->llen = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1llen_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->llen);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1ulen_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->ulen = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1ulen_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->ulen);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1len_1est_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(size_t **)&jarg2; 
  if (arg1) (arg1)->len_est = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1len_1est_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (size_t *) ((arg1)->len_est);
  *(size_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1wkld_1est_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t *arg2 = (size_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(size_t **)&jarg2; 
  if (arg1) (arg1)->wkld_est = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1wkld_1est_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  size_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (size_t *) ((arg1)->wkld_est);
  *(size_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1row_1state_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  byte__t *arg2 = (byte__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(byte__t **)&jarg2; 
  if (arg1) (arg1)->row_state = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1row_1state_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  byte__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (byte__t *) ((arg1)->row_state);
  *(byte__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1lu_1array2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void **arg2 = (void **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void ***)&jarg2; 
  if (arg1) (arg1)->lu_array2 = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1lu_1array2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void **) ((arg1)->lu_array2);
  *(void ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1workspace_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->workspace = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1workspace_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void *) ((arg1)->workspace);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1workspace_1mt1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void **arg2 = (void **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void ***)&jarg2; 
  if (arg1) (arg1)->workspace_mt1 = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1workspace_1mt1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void **) ((arg1)->workspace_mt1);
  *(void ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1workspace_1mt2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void **arg2 = (void **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void ***)&jarg2; 
  if (arg1) (arg1)->workspace_mt2 = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1workspace_1mt2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void **) ((arg1)->workspace_mt2);
  *(void ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1thread_1work_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->thread_work = (int volatile )arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1thread_1work_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (int)(int) ((arg1)->thread_work);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1thread_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->thread_id = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1thread_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void *) ((arg1)->thread_id);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1thread_1arg_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->thread_arg = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1thread_1arg_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void *) ((arg1)->thread_arg);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1thread_1active_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  bool__t *arg2 = (bool__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(bool__t **)&jarg2; 
  if (arg1) (arg1)->thread_active = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1thread_1active_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  bool__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (bool__t *) ((arg1)->thread_active);
  *(bool__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1thread_1finish_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  bool__t *arg2 = (bool__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(bool__t **)&jarg2; 
  if (arg1) (arg1)->thread_finish = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1thread_1finish_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  bool__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (bool__t *) ((arg1)->thread_finish);
  *(bool__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1cluster_1start_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->cluster_start = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1cluster_1start_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->cluster_start);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1cluster_1end_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->cluster_end = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1cluster_1end_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->cluster_end);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1pipeline_1start_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->pipeline_start = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1pipeline_1start_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->pipeline_start);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1pipeline_1end_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->pipeline_end = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1pipeline_1end_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->pipeline_end);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1last_1busy_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->last_busy = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1last_1busy_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->last_busy);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1aeg_1level_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->aeg_level = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1aeg_1level_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->aeg_level);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1aeg_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->aeg_data = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1aeg_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->aeg_data);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1aeg_1header_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->aeg_header = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1aeg_1header_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->aeg_header);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1aeg_1refact_1level_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  if (arg1) (arg1)->aeg_refact_level = arg2;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_SNicsLU_1aeg_1refact_1level_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result =  ((arg1)->aeg_refact_level);
  {
    jresult = (jint)result;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1aeg_1refact_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->aeg_refact_data = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1aeg_1refact_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->aeg_refact_data);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1aeg_1refact_1header_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(uint__t **)&jarg2; 
  if (arg1) (arg1)->aeg_refact_header = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1aeg_1refact_1header_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  uint__t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (uint__t *) ((arg1)->aeg_refact_header);
  *(uint__t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_SNicsLU_1timer_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *arg2 = (void *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  if (arg1) (arg1)->timer = arg2;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_SNicsLU_1timer_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  void *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  result = (void *) ((arg1)->timer);
  *(void **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_nicsluJNI_new_1SNicsLU(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct tagSNicsLU *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct tagSNicsLU *)calloc(1, sizeof(struct tagSNicsLU));
  *(struct tagSNicsLU **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_nicsluJNI_delete_1SNicsLU(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct tagSNicsLU *arg1 = (struct tagSNicsLU *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct tagSNicsLU **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Initialize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_Initialize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Destroy(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_Destroy(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1CreateMatrix(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jlong jarg4, jlong jarg5, jlong jarg6) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  uint__t arg2 ;
  uint__t arg3 ;
  real__t *arg4 = (real__t *) 0 ;
  uint__t *arg5 = (uint__t *) 0 ;
  uint__t *arg6 = (uint__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  {
    arg2 = (uint__t)jarg2;
  }
  {
    arg3 = (uint__t)jarg3;
  }
  arg4 = *(real__t **)&jarg4; 
  arg5 = *(uint__t **)&jarg5; 
  arg6 = *(uint__t **)&jarg6; 
  result = (int)NicsLU_CreateMatrix(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1CreateScheduler(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_CreateScheduler(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1CreateThreads(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jboolean jarg3) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  unsigned int arg2 ;
  bool__t arg3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  {
    arg3 = (bool__t)jarg3;
  }
  result = (int)NicsLU_CreateThreads(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1BindThreads(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jboolean jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  bool__t arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  {
    arg2 = (bool__t)jarg2;
  }
  result = (int)NicsLU_BindThreads(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1DestroyThreads(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_DestroyThreads(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Analyze(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_Analyze(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Factorize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_Factorize(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1ReFactorize(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_ReFactorize(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Factorize_1MT(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  result = (int)NicsLU_Factorize_MT(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1ReFactorize_1MT(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_ReFactorize_MT(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Solve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_Solve(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1SolveFast(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_SolveFast(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1ResetMatrixValues(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_ResetMatrixValues(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Refine(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jdouble jarg4, jint jarg5) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  real__t *arg3 = (real__t *) 0 ;
  real__t arg4 ;
  uint__t arg5 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  arg3 = *(real__t **)&jarg3; 
  {
    arg4 = (real__t)jarg4;
  }
  {
    arg5 = (uint__t)jarg5;
  }
  result = (int)NicsLU_Refine(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Throughput(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_Throughput(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Flops(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_Flops(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1ThreadLoad(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  unsigned int arg2 ;
  real__t **arg3 = (real__t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = (unsigned int)jarg2; 
  arg3 = *(real__t ***)&jarg3; 
  result = (int)NicsLU_ThreadLoad(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1DumpA(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t **arg2 = (real__t **) 0 ;
  uint__t **arg3 = (uint__t **) 0 ;
  uint__t **arg4 = (uint__t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t ***)&jarg2; 
  arg3 = *(uint__t ***)&jarg3; 
  arg4 = *(uint__t ***)&jarg4; 
  result = (int)NicsLU_DumpA(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1DumpLU(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t **arg2 = (real__t **) 0 ;
  uint__t **arg3 = (uint__t **) 0 ;
  size_t **arg4 = (size_t **) 0 ;
  real__t **arg5 = (real__t **) 0 ;
  uint__t **arg6 = (uint__t **) 0 ;
  size_t **arg7 = (size_t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t ***)&jarg2; 
  arg3 = *(uint__t ***)&jarg3; 
  arg4 = *(size_t ***)&jarg4; 
  arg5 = *(real__t ***)&jarg5; 
  arg6 = *(uint__t ***)&jarg6; 
  arg7 = *(size_t ***)&jarg7; 
  result = (int)NicsLU_DumpLU(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1ConditionNumber(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_ConditionNumber(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1MemoryUsage(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  SNicsLU *arg1 = (SNicsLU *) 0 ;
  real__t *arg2 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SNicsLU **)&jarg1; 
  arg2 = *(real__t **)&jarg2; 
  result = (int)NicsLU_MemoryUsage(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Residual(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jint jarg8, jint jarg9) {
  jint jresult = 0 ;
  uint__t arg1 ;
  real__t *arg2 = (real__t *) 0 ;
  uint__t *arg3 = (uint__t *) 0 ;
  uint__t *arg4 = (uint__t *) 0 ;
  real__t *arg5 = (real__t *) 0 ;
  real__t *arg6 = (real__t *) 0 ;
  real__t *arg7 = (real__t *) 0 ;
  int arg8 ;
  int arg9 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (uint__t)jarg1;
  }
  arg2 = *(real__t **)&jarg2; 
  arg3 = *(uint__t **)&jarg3; 
  arg4 = *(uint__t **)&jarg4; 
  arg5 = *(real__t **)&jarg5; 
  arg6 = *(real__t **)&jarg6; 
  arg7 = *(real__t **)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = (int)jarg9; 
  result = (int)NicsLU_Residual(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Transpose(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  uint__t arg1 ;
  uint__t arg2 ;
  real__t *arg3 = (real__t *) 0 ;
  uint__t *arg4 = (uint__t *) 0 ;
  uint__t *arg5 = (uint__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (uint__t)jarg1;
  }
  {
    arg2 = (uint__t)jarg2;
  }
  arg3 = *(real__t **)&jarg3; 
  arg4 = *(uint__t **)&jarg4; 
  arg5 = *(uint__t **)&jarg5; 
  result = (int)NicsLU_Transpose(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1Sort(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  uint__t arg1 ;
  uint__t arg2 ;
  real__t *arg3 = (real__t *) 0 ;
  uint__t *arg4 = (uint__t *) 0 ;
  uint__t *arg5 = (uint__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (uint__t)jarg1;
  }
  {
    arg2 = (uint__t)jarg2;
  }
  arg3 = *(real__t **)&jarg3; 
  arg4 = *(uint__t **)&jarg4; 
  arg5 = *(uint__t **)&jarg5; 
  result = (int)NicsLU_Sort(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_NicsLU_1MergeDuplicateEntries(JNIEnv *jenv, jclass jcls, jint jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  uint__t arg1 ;
  uint__t *arg2 = (uint__t *) 0 ;
  real__t **arg3 = (real__t **) 0 ;
  uint__t **arg4 = (uint__t **) 0 ;
  uint__t **arg5 = (uint__t **) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  {
    arg1 = (uint__t)jarg1;
  }
  arg2 = *(uint__t **)&jarg2; 
  arg3 = *(real__t ***)&jarg3; 
  arg4 = *(uint__t ***)&jarg4; 
  arg5 = *(uint__t ***)&jarg5; 
  result = (int)NicsLU_MergeDuplicateEntries(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_nicsluJNI_readFromFile(JNIEnv *jenv, jclass jcls, jstring jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jlong jarg6, jlong jarg7, jlong jarg8) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  uint__t *arg2 = (uint__t *) 0 ;
  uint__t *arg3 = (uint__t *) 0 ;
  uint__t *arg4 = (uint__t *) 0 ;
  uint__t *arg5 = (uint__t *) 0 ;
  real__t *arg6 = (real__t *) 0 ;
  real__t *arg7 = (real__t *) 0 ;
  real__t *arg8 = (real__t *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  arg2 = *(uint__t **)&jarg2; 
  arg3 = *(uint__t **)&jarg3; 
  arg4 = *(uint__t **)&jarg4; 
  arg5 = *(uint__t **)&jarg5; 
  arg6 = *(real__t **)&jarg6; 
  arg7 = *(real__t **)&jarg7; 
  arg8 = *(real__t **)&jarg8; 
  result = (int)readFromFile(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


#ifdef __cplusplus
}
#endif

