/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class nicslulib implements nicslulibConstants {
  public static int NicsLU_Initialize(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_Initialize(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_Destroy(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_Destroy(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_CreateMatrix(SNicsLU nicslu, int n, int nnz, SWIGTYPE_p_real__t ax, SWIGTYPE_p_uint__t ai, SWIGTYPE_p_uint__t ap) {
    return nicslulibJNI.NicsLU_CreateMatrix(SNicsLU.getCPtr(nicslu), nicslu, n, nnz, SWIGTYPE_p_real__t.getCPtr(ax), SWIGTYPE_p_uint__t.getCPtr(ai), SWIGTYPE_p_uint__t.getCPtr(ap));
  }

  public static int NicsLU_CreateScheduler(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_CreateScheduler(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_CreateThreads(SNicsLU nicslu, long threads, boolean check) {
    return nicslulibJNI.NicsLU_CreateThreads(SNicsLU.getCPtr(nicslu), nicslu, threads, check);
  }

  public static int NicsLU_BindThreads(SNicsLU nicslu, boolean unbind) {
    return nicslulibJNI.NicsLU_BindThreads(SNicsLU.getCPtr(nicslu), nicslu, unbind);
  }

  public static int NicsLU_DestroyThreads(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_DestroyThreads(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_Analyze(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_Analyze(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_Factorize(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_Factorize(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_ReFactorize(SNicsLU nicslu, SWIGTYPE_p_real__t ax) {
    return nicslulibJNI.NicsLU_ReFactorize(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(ax));
  }

  public static int NicsLU_Factorize_MT(SNicsLU nicslu) {
    return nicslulibJNI.NicsLU_Factorize_MT(SNicsLU.getCPtr(nicslu), nicslu);
  }

  public static int NicsLU_ReFactorize_MT(SNicsLU nicslu, SWIGTYPE_p_real__t ax) {
    return nicslulibJNI.NicsLU_ReFactorize_MT(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(ax));
  }

  public static int NicsLU_Solve(SNicsLU nicslu, SWIGTYPE_p_real__t rhs) {
    return nicslulibJNI.NicsLU_Solve(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(rhs));
  }

  public static int NicsLU_SolveFast(SNicsLU nicslu, SWIGTYPE_p_real__t rhs) {
    return nicslulibJNI.NicsLU_SolveFast(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(rhs));
  }

  public static int NicsLU_ResetMatrixValues(SNicsLU nicslu, SWIGTYPE_p_real__t ax) {
    return nicslulibJNI.NicsLU_ResetMatrixValues(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(ax));
  }

  public static int NicsLU_Refine(SNicsLU nicslu, SWIGTYPE_p_real__t x, SWIGTYPE_p_real__t b, double eps, int maxiter) {
    return nicslulibJNI.NicsLU_Refine(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(x), SWIGTYPE_p_real__t.getCPtr(b), eps, maxiter);
  }

  public static int NicsLU_Throughput(SNicsLU nicslu, SWIGTYPE_p_real__t thr) {
    return nicslulibJNI.NicsLU_Throughput(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(thr));
  }

  public static int NicsLU_Flops(SNicsLU nicslu, SWIGTYPE_p_real__t flops) {
    return nicslulibJNI.NicsLU_Flops(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(flops));
  }

  public static int NicsLU_ThreadLoad(SNicsLU nicslu, long threads, SWIGTYPE_p_p_real__t thread_flops) {
    return nicslulibJNI.NicsLU_ThreadLoad(SNicsLU.getCPtr(nicslu), nicslu, threads, SWIGTYPE_p_p_real__t.getCPtr(thread_flops));
  }

  public static int NicsLU_DumpA(SNicsLU nicslu, SWIGTYPE_p_p_real__t ax, SWIGTYPE_p_p_uint__t ai, SWIGTYPE_p_p_uint__t ap) {
    return nicslulibJNI.NicsLU_DumpA(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_p_real__t.getCPtr(ax), SWIGTYPE_p_p_uint__t.getCPtr(ai), SWIGTYPE_p_p_uint__t.getCPtr(ap));
  }

  public static int NicsLU_DumpLU(SNicsLU nicslu, SWIGTYPE_p_p_real__t lx, SWIGTYPE_p_p_uint__t li, SWIGTYPE_p_p_size_t lp, SWIGTYPE_p_p_real__t ux, SWIGTYPE_p_p_uint__t ui, SWIGTYPE_p_p_size_t up) {
    return nicslulibJNI.NicsLU_DumpLU(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_p_real__t.getCPtr(lx), SWIGTYPE_p_p_uint__t.getCPtr(li), SWIGTYPE_p_p_size_t.getCPtr(lp), SWIGTYPE_p_p_real__t.getCPtr(ux), SWIGTYPE_p_p_uint__t.getCPtr(ui), SWIGTYPE_p_p_size_t.getCPtr(up));
  }

  public static int NicsLU_ConditionNumber(SNicsLU nicslu, SWIGTYPE_p_real__t cond) {
    return nicslulibJNI.NicsLU_ConditionNumber(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(cond));
  }

  public static int NicsLU_MemoryUsage(SNicsLU nicslu, SWIGTYPE_p_real__t memuse) {
    return nicslulibJNI.NicsLU_MemoryUsage(SNicsLU.getCPtr(nicslu), nicslu, SWIGTYPE_p_real__t.getCPtr(memuse));
  }

  public static int NicsLU_Residual(int n, SWIGTYPE_p_real__t ax, SWIGTYPE_p_uint__t ai, SWIGTYPE_p_uint__t ap, SWIGTYPE_p_real__t x, SWIGTYPE_p_real__t b, SWIGTYPE_p_real__t error, int norm, int mode) {
    return nicslulibJNI.NicsLU_Residual(n, SWIGTYPE_p_real__t.getCPtr(ax), SWIGTYPE_p_uint__t.getCPtr(ai), SWIGTYPE_p_uint__t.getCPtr(ap), SWIGTYPE_p_real__t.getCPtr(x), SWIGTYPE_p_real__t.getCPtr(b), SWIGTYPE_p_real__t.getCPtr(error), norm, mode);
  }

  public static int NicsLU_Transpose(int n, int nnz, SWIGTYPE_p_real__t ax, SWIGTYPE_p_uint__t ai, SWIGTYPE_p_uint__t ap) {
    return nicslulibJNI.NicsLU_Transpose(n, nnz, SWIGTYPE_p_real__t.getCPtr(ax), SWIGTYPE_p_uint__t.getCPtr(ai), SWIGTYPE_p_uint__t.getCPtr(ap));
  }

  public static int NicsLU_Sort(int n, int nnz, SWIGTYPE_p_real__t ax, SWIGTYPE_p_uint__t ai, SWIGTYPE_p_uint__t ap) {
    return nicslulibJNI.NicsLU_Sort(n, nnz, SWIGTYPE_p_real__t.getCPtr(ax), SWIGTYPE_p_uint__t.getCPtr(ai), SWIGTYPE_p_uint__t.getCPtr(ap));
  }

  public static int NicsLU_MergeDuplicateEntries(int n, SWIGTYPE_p_uint__t nnz, SWIGTYPE_p_p_real__t ax, SWIGTYPE_p_p_uint__t ai, SWIGTYPE_p_p_uint__t ap) {
    return nicslulibJNI.NicsLU_MergeDuplicateEntries(n, SWIGTYPE_p_uint__t.getCPtr(nnz), SWIGTYPE_p_p_real__t.getCPtr(ax), SWIGTYPE_p_p_uint__t.getCPtr(ai), SWIGTYPE_p_p_uint__t.getCPtr(ap));
  }

  public static int readFromFile(String file, SWIGTYPE_p_uint__t n, SWIGTYPE_p_uint__t nnz, SWIGTYPE_p_uint__t ai, SWIGTYPE_p_uint__t ap, SWIGTYPE_p_real__t ax, SWIGTYPE_p_real__t x, SWIGTYPE_p_real__t b) {
    return nicslulibJNI.readFromFile(file, SWIGTYPE_p_uint__t.getCPtr(n), SWIGTYPE_p_uint__t.getCPtr(nnz), SWIGTYPE_p_uint__t.getCPtr(ai), SWIGTYPE_p_uint__t.getCPtr(ap), SWIGTYPE_p_real__t.getCPtr(ax), SWIGTYPE_p_real__t.getCPtr(x), SWIGTYPE_p_real__t.getCPtr(b));
  }

}
