package wrapper;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface nicsluConstants {
  public final static int NICSLU_GENERAL_FAIL = nicsluJNI.NICSLU_GENERAL_FAIL_get();
  public final static int NICSLU_ARGUMENT_ERROR = nicsluJNI.NICSLU_ARGUMENT_ERROR_get();
  public final static int NICSLU_MEMORY_OVERFLOW = nicsluJNI.NICSLU_MEMORY_OVERFLOW_get();
  public final static int NICSLU_FILE_CANNOT_OPEN = nicsluJNI.NICSLU_FILE_CANNOT_OPEN_get();
  public final static int NICSLU_MATRIX_STRUCTURAL_SINGULAR = nicsluJNI.NICSLU_MATRIX_STRUCTURAL_SINGULAR_get();
  public final static int NICSLU_MATRIX_NUMERIC_SINGULAR = nicsluJNI.NICSLU_MATRIX_NUMERIC_SINGULAR_get();
  public final static int NICSLU_MATRIX_INVALID = nicsluJNI.NICSLU_MATRIX_INVALID_get();
  public final static int NICSLU_MATRIX_ENTRY_DUPLICATED = nicsluJNI.NICSLU_MATRIX_ENTRY_DUPLICATED_get();
  public final static int NICSLU_THREADS_NOT_INITIALIZED = nicsluJNI.NICSLU_THREADS_NOT_INITIALIZED_get();
  public final static int NICSLU_MATRIX_NOT_INITIALIZED = nicsluJNI.NICSLU_MATRIX_NOT_INITIALIZED_get();
  public final static int NICSLU_SCHEDULER_NOT_INITIALIZED = nicsluJNI.NICSLU_SCHEDULER_NOT_INITIALIZED_get();
  public final static int NICSLU_SINGLE_THREAD = nicsluJNI.NICSLU_SINGLE_THREAD_get();
  public final static int NICSLU_THREADS_INIT_FAIL = nicsluJNI.NICSLU_THREADS_INIT_FAIL_get();
  public final static int NICSLU_MATRIX_NOT_ANALYZED = nicsluJNI.NICSLU_MATRIX_NOT_ANALYZED_get();
  public final static int NICSLU_MATRIX_NOT_FACTORIZED = nicsluJNI.NICSLU_MATRIX_NOT_FACTORIZED_get();
  public final static int NICSLU_NUMERIC_OVERFLOW = nicsluJNI.NICSLU_NUMERIC_OVERFLOW_get();
  public final static int NICSLU_USE_SEQUENTIAL_FACTORIZATION = nicsluJNI.NICSLU_USE_SEQUENTIAL_FACTORIZATION_get();
  public final static int NICSLU_BIND_THREADS_FAIL = nicsluJNI.NICSLU_BIND_THREADS_FAIL_get();
}
