package wrapper;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface nicslu_readfileConstants {
  public final static int ROW_LENGTH = nicslu_readfileJNI.ROW_LENGTH_get();
}
