package wrapper;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SWIGTYPE_p_byte__t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_byte__t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_byte__t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_byte__t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

