package wrapper;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class uintArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected uintArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(uintArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        nicsluJNI.delete_uintArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public uintArray(int nelements) {
    this(nicsluJNI.new_uintArray(nelements), true);
  }

  public int getitem(int index) { return nicsluJNI.uintArray_getitem(swigCPtr, this, index); }

  public void setitem(int index, int value) {
    nicsluJNI.uintArray_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_uint__t cast() {
    long cPtr = nicsluJNI.uintArray_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint__t(cPtr, false);
  }

  public static uintArray frompointer(SWIGTYPE_p_uint__t t) {
    long cPtr = nicsluJNI.uintArray_frompointer(SWIGTYPE_p_uint__t.getCPtr(t));
    return (cPtr == 0) ? null : new uintArray(cPtr, false);
  }

}
